# Copyright 2009 Google Inc. All Rights Reserved.
# Author: lenjoy@google.com (Lenjoy)
#
# Package:
#   experimental/users/lenjoy/algoutil
#
# Description:
#   TODO(lenjoy): describe this package.

cc_library(name = "stringutil",
           srcs = [ "stringutil.cc" ],
           deps = []
           )

cc_test(name = "stringutil_test",
        srcs = [ "stringutil_test.cc" ],
        deps = [ ":stringutil",
                 "//testing/base/public:gunit_main" ]
        )
