<?php

/*

Please see gpl.txt for licence and disclaimer of warranty.

Seemes CMS
Copyright 2007, 2008 Samuel C
Filename: login.inc
Description: Login page.

*/

?>
<h2>Administrator Login</h2>
<form action="login.php" method="post">
<fieldset>
<label for="loginpassword">Password:</label><br />
<input type="password" name="loginpassword" id="loginpassword" /><br />
<input type="submit" value="Log in" />
</fieldset>
</form>