application: heycycle
version: 1
runtime: python
api_version: 1

handlers:
- url: /docron
  script: docron.py

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /.*
  script: heycycle.py
